public with sharing class Constant {

    public static final String SEARCH_DEFAULT_TEXT = 'Search';
    public static final String SEARCH_BRAND_DEFAULT_TEXT = 'Search for Brands';
    
    // Profiles
    public static final String PROFILE_NAME_INTERNAL = 'Diageo Portal User';
    
    public static final String MARKET = 'Market';
    public static final String DISTRIBUTOR = 'Distributor';
    
   	// Top level
    public static final String MONTHLY_EXECUTION_PLAN = 'Monthly Execution Plan';
    public static final String INNOVATION_AND_SUSTAINOVATION = 'Innovation, Sustainovation & VAP';
    public static final String INNOVATION_SUSTAINOVATION_AND_VINTAGE = 'Innovation, Sustainovation & Vintage Transition';
    public static final String SELLING_MATERILAS = 'Selling Materials';
    public static final String PERFORMANCE_MANAGMENT = 'Performance Management';
	public static final String BRAND_MARKETING_INFORMATION = 'Brand Marketing Information';      
    public static final String PRODUCT_IMAGES_AND_LOGOS = 'Product Images & Logos';
    public static final String POS = 'POS';
    public static final String LINKS = 'Links';
	public static final String FAQ = 'FAQ';
	public static final String CASES = 'Cases';
	public static final String COLLABORATION = 'Collaboration';
	public static final String DWS = 'DWS';
	public static final String DIAGEOWINESCOM = 'diageowines.com';
	public static final String PLANNING = 'Planning';


	// Monthly Execution Plan
	public static final String VIDEOS_AND_MEDIA = 'Media';
	public static final String SELL_SHEETS = 'Selling Materials';
	public static final String OTHERS = 'General';


	// Innovation, Sustainovation & VAP
	public static final String SUSTAINOVATION = 'Sustainovation';
	public static final String VAP = 'VAP';
	public static final String PACK_AND_LABELS = 'Pack & Label Changes';
	public static final String PERFORMANCE_UPDATES = 'Performance Updates';
	public static final String PLANNING_CALENDARS = 'Planning Calendars';
    public static final String INNOVATION = 'Innovation';	
    public static final String BRAND_FACT_SHEETS = 'Brand Fact Sheet';
	public static final String MARKETING_INFORMATION = 'Marketing Information';
	public static final String MARKETING_DECK = 'Marketing Deck';
	public static final String RETAIL_MAILERS = 'Retail Mailers';

	public static final String IMAGES = 'Images';
	public static final String LOGO_SHOTS = 'Logo Shots';
	public static final String SCANNABLE_UPC = 'Scannable UPC';

	public static final String SHIPPING_DETAILS = 'Shipping Details';
	public static final String ALLOCATIONS = 'Allocations';
	public static final String SOURCE_POINTS = 'Source Points';
	public static final String SAMPLES = 'Samples';
	public static final String ORDERABILITY = 'Orderability';

	public static final String PRELIMINARY_LONG_LEAD_DECK = 'Preliminary Long Lead Deck';
	public static final String FINAL_LAUNCH_DECK = 'Final Launch Deck';
	public static final String LAUNCH_SELL_SHEET = 'Launch Sell Sheet';
	public static final String BUSINESS_CARD_AND_HOT_SHEET = 'Business Card / Hot Sheet';

	public static final String FORECASTING = 'Forecasting';
	public static final String SUCCESS_STORIES = 'Success Stories';

		
	// Selling Materials
	public static final String QUARTERLY_SELLING_MATERIALS = 'Quarterly Selling Materials';
	public static final String SELLING_SOLUTIONS = 'Category Selling Solutions';
	public static final String STANDARDS = 'Standards';
	//-----------
	public static final String PORTFOLIO_ACTIVATIONS = 'Portfolio Activations';
	public static final String EASE_OF_SHOP = 'Ease of Shop';
	public static final String CATEGOTY_DEVELOPMENT = 'Category Development';	
	public static final String PROGRAM_SELLING_MATERIALS = 'Program Selling Materials';
	public static final String INNOVATION_AND_VAP_SELLING_MATERIALS = 'Innovation & VAP Selling Materials';
	public static final String DIVISION_SPECYFIC_CAT_DEV = 'Division Specific Cat Dev';
	// Performance Management
	// none...
		
	// Brand Marketing Information
	public static final String PROGRAMMING = 'Programming';
	public static final String CURRENT_PROGRAMMING = 'Current Programming';
	public static final String FACT_SHEETS = 'Fact Sheets';
	public static final String MULTICULTURAL = 'Multicultural';
	public static final String MEDIA = 'Media';
    public static final String TRADE_ADS = 'Trade Ads';
    	
	// Product Images & Logos
	public static final String DRINK_SHOTS = 'Drink Shots';
	public static final String LOGOS = 'Logos';
	public static final String PRODUCT_SHOTS = 'Product Shots';
	public static final String FAMILY_SHOTS = 'Family Shots';
	public static final String ONEL = '1.5 L';
	public static final String SEVML = '750 ml';
	public static final String THRML = '350 ml';

	// Planning
	public static final String SPIRITS_PLANNING = 'Spirits Planning';
	public static final String WINE_PLANNING = 'Wine Planning';
	public static final String NATIONAL_ACCOUNTS = 'National Accounts';
		
	// POS
	// none...
	
	// Multicultural
	public static final String MULTICULTURAL_PROGRAMS = 'Multicultural Programs';
	public static final String TOOLS = 'Tools';
	public static final String CONSUMER_INFO = 'Consumer Info';
	public static final String BEST_PRACTICES = 'Best Practices';
    public static final String MULTICULTURAL_CALENDAR_SELLING_MATERIALS = 'Selling Materials';
    public static final String MULTICULTURAL_CALENDAR_OTHER = 'Other';    
	// Others
    public static final String RUMS_AND_CORDIALS = 'Rums and Cordials';
    public static final String WHISKIES = 'Whiskies';    
    public static final String VODKAS = 'Vodkas';
    public static final String GIN_AND_COCKTAILS = 'Gin and Cocktails';
    public static final String TEQUILAS = 'Tequilas';	
	// -----------------------------------------------------
	public static final String PROGRAM = 'Program';
    public static final String PROGRAM_OVERVIEW = 'Program Overview';
	public static final String PROGRAM_BRIEF = 'Program Brief';
	public static final String PROGRAM_SELL_SHEET = 'Program Sell Sheet';
	// -----------------------------------------------------
    public static final String LUNCH_DECK = 'Lunch Decks';
    public static final String INNOVATION_SELL_SHEET = 'Innovation Sell Sheet';
    // -----------------------------------------------------
    public static final String COMMERCIALS = 'TV Commercials';
    public static final String CHARTS = 'Flow Charts';
    public static final String PR = 'PR';
    public static final String DIGITAL = 'Digital';
    public static final String SIZZLE = 'Sizzle Reels';
    public static final String OOH = 'OOH Creative';
    public static final String RADIO = 'Radio'; 
    public static final String PRINT = 'Print'; 
    public static final String MISC_MEDIA = 'Misc Media';
	// -----------------------------------------------------
	public static final String PROGRAM_EXECUTION_STANDARDS = 'Program Execution Standards';
	public static final String MEDIA_SELL_SHEET = 'Media Sell Sheet';
	// -----------------------------------------------------
    public static final String ON_PREMISE = 'On Premise';
    public static final String OFF_PREMISE = 'Off Premise';
	public static final String SHELF = 'Shelf';
	public static final String PLANNOGRAMS = 'Plannograms';	
	public static final String DISPLAY = 'Display & Merchandising';	 
	// -----------------------------------------------------
    public static final String COUPONS = 'Coupons';
    
    public static final String COMPLIANCE = 'Compliance';
    public static final String TERMS_AND_CONDITIONS = 'Terms & Conditions';
    public static final String PRIVACY_POLICY = 'Privacy Policy';
    public static final String CODES_POLICIES = 'Codes & Policies';

	// PLANNING LAYOUT TYPEs
    public static final String PLANNING_STANDARD = 'Standard';
    public static final String PLANNING_SIMPLE_CALENDAR = 'Calendar';
	public static final String PLANNING_CALENDAR = 'Calendar With Columns';
	
	
	// CLASSIFICATION VALUES (Selling materials)
	// FOR PSM
    public static final String CLS_PXB = 'Execution Brief';
    public static final String CLS_PXSOFP = 'Execution Standards – Off Premise';
    public static final String CLS_PXSONP = 'Execution Standards – On Premise';
    public static final String CLS_PXSMS = 'Execution Standards – Monthly Summary';
    public static final String CLS_PSD = 'Selling Deck';
    public static final String CLS_FS = 'Fact Sheet';
    public static final String CLS_INP = 'Integrated National Program';
    public static final String CLS_D = 'Distribution';
    public static final String CLS_DV = 'Display/Visibility';
    public static final String CLS_I = 'Innovation';
    public static final String CLS_S = 'Sustainovation';
	// FOR IVAP
    public static final String CLS_PLLD = 'Preliminary Long Lead Deck';
    public static final String CLS_FLD = 'Final Launch Deck';
    public static final String CLS_LSS = 'Launch Sell Sheet';
    public static final String CLS_BCHS = 'Business Card / Hot Sheet';
    public static final String CLS_F = 'Forecasting';
    public static final String CLS_TA = 'Trade Ad';
    public static final String CLS_V = 'VAP';
    
    // For Content Workspace
    public static final String COLLABORATION_LIBRARY = 'Collaboration';
    public static final String DISTRIBUTOR_PORTAL_LIBRARY = 'Distributor Portal';
}