/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 * Created by Akanksha(offshore) for case  00003540
 **/
@isTest
private class Test_Controller_OppurtunityWhitespace {
	/*
    static testMethod void myUnitTest() {
       Account accountData = Test_Helper.testInsertAccount('accountNeme');
       NABCA_Opportunity__c opp = new NABCA_Opportunity__c(account__c = accountData.id, Opportunity_Composite_Key__c = accountData.id);
       insert opp;
       ApexPages.StandardController sc = new ApexPages.StandardController(accountData);
	   Controller_OppurtunityWhitespace controller = new Controller_OppurtunityWhitespace(sc);
    }*/
}